//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 06:59:16 PM ICT 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for column complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="column">
 *   &lt;complexContent>
 *     &lt;extension base="{}field">
 *       &lt;sequence>
 *         &lt;element name="Valid" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ValidationRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AlternateValues">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AlternateValue" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "column", propOrder = {
    "valid",
    "validationRequired",
    "alternateValues"
})
public class Column
    extends Field
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "Valid")
    protected boolean valid;
    @XmlElement(name = "ValidationRequired")
    protected boolean validationRequired;
    @XmlElement(name = "AlternateValues", required = true)
    protected Column.AlternateValues alternateValues;

    /**
     * Gets the value of the valid property.
     * 
     */
    public boolean isValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     */
    public void setValid(boolean value) {
        this.valid = value;
    }

    /**
     * Gets the value of the validationRequired property.
     * 
     */
    public boolean isValidationRequired() {
        return validationRequired;
    }

    /**
     * Sets the value of the validationRequired property.
     * 
     */
    public void setValidationRequired(boolean value) {
        this.validationRequired = value;
    }

    /**
     * Gets the value of the alternateValues property.
     * 
     * @return
     *     possible object is
     *     {@link Column.AlternateValues }
     *     
     */
    public Column.AlternateValues getAlternateValues() {
        return alternateValues;
    }

    /**
     * Sets the value of the alternateValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Column.AlternateValues }
     *     
     */
    public void setAlternateValues(Column.AlternateValues value) {
        this.alternateValues = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AlternateValue" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alternateValue"
    })
    public static class AlternateValues
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "AlternateValue")
        protected List<Field> alternateValue;

        /**
         * Gets the value of the alternateValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the alternateValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAlternateValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Field }
         * 
         * 
         */
        public List<Field> getAlternateValue() {
            if (alternateValue == null) {
                alternateValue = new ArrayList<Field>();
            }
            return this.alternateValue;
        }

    }

}
