//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 06:59:16 PM ICT 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for docField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="docField">
 *   &lt;complexContent>
 *     &lt;extension base="{}field">
 *       &lt;sequence>
 *         &lt;element name="AlternateValues">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AlternateValue" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PreviousValue" type="{}docField"/>
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="widgetType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scriptEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "docField", propOrder = {
    "alternateValues",
    "previousValue",
    "category",
    "hidden",
    "widgetType",
    "scriptEnabled",
    "message"
})
public class DocField
    extends Field
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "AlternateValues", required = true)
    protected DocField.AlternateValues alternateValues;
    @XmlElement(name = "PreviousValue", required = true)
    protected DocField previousValue;
    @XmlElement(name = "Category", required = true)
    protected String category;
    protected boolean hidden;
    @XmlElement(required = true)
    protected String widgetType;
    protected boolean scriptEnabled;
    @XmlElement(name = "Message", required = true)
    protected String message;

    /**
     * Gets the value of the alternateValues property.
     * 
     * @return
     *     possible object is
     *     {@link DocField.AlternateValues }
     *     
     */
    public DocField.AlternateValues getAlternateValues() {
        return alternateValues;
    }

    /**
     * Sets the value of the alternateValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocField.AlternateValues }
     *     
     */
    public void setAlternateValues(DocField.AlternateValues value) {
        this.alternateValues = value;
    }

    /**
     * Gets the value of the previousValue property.
     * 
     * @return
     *     possible object is
     *     {@link DocField }
     *     
     */
    public DocField getPreviousValue() {
        return previousValue;
    }

    /**
     * Sets the value of the previousValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocField }
     *     
     */
    public void setPreviousValue(DocField value) {
        this.previousValue = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the hidden property.
     * 
     */
    public boolean isHidden() {
        return hidden;
    }

    /**
     * Sets the value of the hidden property.
     * 
     */
    public void setHidden(boolean value) {
        this.hidden = value;
    }

    /**
     * Gets the value of the widgetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidgetType() {
        return widgetType;
    }

    /**
     * Sets the value of the widgetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidgetType(String value) {
        this.widgetType = value;
    }

    /**
     * Gets the value of the scriptEnabled property.
     * 
     */
    public boolean isScriptEnabled() {
        return scriptEnabled;
    }

    /**
     * Sets the value of the scriptEnabled property.
     * 
     */
    public void setScriptEnabled(boolean value) {
        this.scriptEnabled = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AlternateValue" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alternateValue"
    })
    public static class AlternateValues
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "AlternateValue")
        protected List<Field> alternateValue;

        /**
         * Gets the value of the alternateValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the alternateValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAlternateValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Field }
         * 
         * 
         */
        public List<Field> getAlternateValue() {
            if (alternateValue == null) {
                alternateValue = new ArrayList<Field>();
            }
            return this.alternateValue;
        }

    }

}
