//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 06:59:16 PM ICT 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Module" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="WorkflowName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ModuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "module"
})
@XmlRootElement(name = "Modules")
public class Modules
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "Module")
    protected List<Modules.Module> module;

    /**
     * Gets the value of the module property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the module property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Modules.Module }
     * 
     * 
     */
    public List<Modules.Module> getModule() {
        if (module == null) {
            module = new ArrayList<Modules.Module>();
        }
        return this.module;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="WorkflowName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ModuleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "workflowName",
        "moduleName"
    })
    public static class Module
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "WorkflowName", required = true)
        protected String workflowName;
        @XmlElement(name = "ModuleName", required = true)
        protected String moduleName;

        /**
         * Gets the value of the workflowName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkflowName() {
            return workflowName;
        }

        /**
         * Sets the value of the workflowName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkflowName(String value) {
            this.workflowName = value;
        }

        /**
         * Gets the value of the moduleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModuleName() {
            return moduleName;
        }

        /**
         * Sets the value of the moduleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModuleName(String value) {
            this.moduleName = value;
        }

    }

}
