//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 06:59:16 PM ICT 
//


package com.ephesoft.dcma.batch.schema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for page complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="page">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OldFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NewFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PageLevelFields">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PageLevelField" type="{}docField" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HocrFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ThumbnailFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ComparisonThumbnailFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DisplayFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OCRInputFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Direction" type="{http://www.ephesoft.com/batch/direction}direction"/>
 *         &lt;element name="IsRotated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "page", propOrder = {
    "identifier",
    "oldFileName",
    "newFileName",
    "pageLevelFields",
    "hocrFileName",
    "thumbnailFileName",
    "comparisonThumbnailFileName",
    "displayFileName",
    "ocrInputFileName",
    "direction",
    "isRotated"
})
public class Page
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "Identifier", required = true)
    protected String identifier;
    @XmlElement(name = "OldFileName", required = true)
    protected String oldFileName;
    @XmlElement(name = "NewFileName", required = true)
    protected String newFileName;
    @XmlElement(name = "PageLevelFields", required = true)
    protected Page.PageLevelFields pageLevelFields;
    @XmlElement(name = "HocrFileName", required = true)
    protected String hocrFileName;
    @XmlElement(name = "ThumbnailFileName", required = true)
    protected String thumbnailFileName;
    @XmlElement(name = "ComparisonThumbnailFileName", required = true)
    protected String comparisonThumbnailFileName;
    @XmlElement(name = "DisplayFileName", required = true)
    protected String displayFileName;
    @XmlElement(name = "OCRInputFileName", required = true)
    protected String ocrInputFileName;
    @XmlElement(name = "Direction", required = true)
    protected Direction direction;
    @XmlElement(name = "IsRotated")
    protected boolean isRotated;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the oldFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldFileName() {
        return oldFileName;
    }

    /**
     * Sets the value of the oldFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldFileName(String value) {
        this.oldFileName = value;
    }

    /**
     * Gets the value of the newFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewFileName() {
        return newFileName;
    }

    /**
     * Sets the value of the newFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewFileName(String value) {
        this.newFileName = value;
    }

    /**
     * Gets the value of the pageLevelFields property.
     * 
     * @return
     *     possible object is
     *     {@link Page.PageLevelFields }
     *     
     */
    public Page.PageLevelFields getPageLevelFields() {
        return pageLevelFields;
    }

    /**
     * Sets the value of the pageLevelFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Page.PageLevelFields }
     *     
     */
    public void setPageLevelFields(Page.PageLevelFields value) {
        this.pageLevelFields = value;
    }

    /**
     * Gets the value of the hocrFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHocrFileName() {
        return hocrFileName;
    }

    /**
     * Sets the value of the hocrFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHocrFileName(String value) {
        this.hocrFileName = value;
    }

    /**
     * Gets the value of the thumbnailFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbnailFileName() {
        return thumbnailFileName;
    }

    /**
     * Sets the value of the thumbnailFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbnailFileName(String value) {
        this.thumbnailFileName = value;
    }

    /**
     * Gets the value of the comparisonThumbnailFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComparisonThumbnailFileName() {
        return comparisonThumbnailFileName;
    }

    /**
     * Sets the value of the comparisonThumbnailFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComparisonThumbnailFileName(String value) {
        this.comparisonThumbnailFileName = value;
    }

    /**
     * Gets the value of the displayFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayFileName() {
        return displayFileName;
    }

    /**
     * Sets the value of the displayFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayFileName(String value) {
        this.displayFileName = value;
    }

    /**
     * Gets the value of the ocrInputFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOCRInputFileName() {
        return ocrInputFileName;
    }

    /**
     * Sets the value of the ocrInputFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOCRInputFileName(String value) {
        this.ocrInputFileName = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link Direction }
     *     
     */
    public Direction getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Direction }
     *     
     */
    public void setDirection(Direction value) {
        this.direction = value;
    }

    /**
     * Gets the value of the isRotated property.
     * 
     */
    public boolean isIsRotated() {
        return isRotated;
    }

    /**
     * Sets the value of the isRotated property.
     * 
     */
    public void setIsRotated(boolean value) {
        this.isRotated = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PageLevelField" type="{}docField" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pageLevelField"
    })
    public static class PageLevelFields
        implements Serializable
    {

        private final static long serialVersionUID = 100L;
        @XmlElement(name = "PageLevelField")
        protected List<DocField> pageLevelField;

        /**
         * Gets the value of the pageLevelField property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pageLevelField property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPageLevelField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocField }
         * 
         * 
         */
        public List<DocField> getPageLevelField() {
            if (pageLevelField == null) {
                pageLevelField = new ArrayList<DocField>();
            }
            return this.pageLevelField;
        }

    }

}
